name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Verify module
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || (echo '::error::go.mod/go.sum changed after tidy' && exit 1)

      - name: Run tests
        run: go test ./... -race -short

      - name: Build validation
        run: go build ./...

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          body: |
            ## Installation
            
            ```bash
            go get github.com/${{ github.repository }}@${{ github.ref_name }}
            ```
