name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Tidy
        run: |
          go mod tidy
          git diff --exit-code || (echo 'go.mod/go.sum changed after tidy' && exit 1)
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -race
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

