name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || (echo '::error::go.mod/go.sum changed after tidy' && exit 1)

      - name: Test
        run: go test ./... -race -short

      - name: Build
        run: go build ./...

